### ISSUE TITLE
Suggest to loosen the dependency on docker

### ISSUE THREAD

**Issue by Agnes-U** [aws-samples/nlp-textract-comprehend-demo#7]
Hi, your project nlp-textract-comprehend-demo(commit id: 69d93dc03bf14e6987f48a5a908f0f88bece34c6) requires "docker==4.3.0" in its dependency. After analyzing the source code, we found that the following versions of docker can also be suitable, i.e., docker 4.2.0, 4.2.1, 4.2.2, since all functions that you directly (5 APIs: docker.api.build.BuildApiMixin.build, docker.api.image.ImageApiMixin.tag, docker.api.image.ImageApiMixin.push, docker.api.client.APIClient.__init__, docker.api.image.ImageApiMixin.remove_image) or indirectly (propagate to 38 docker's internal APIs and 27 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on docker from "docker==4.3.0" to "docker>=4.2.0,<=4.3.0". This will improve the applicability of nlp-textract-comprehend-demo and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on docker?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by ernesto-santos** [comment]
Hi Agnes,

Thanks for your suggestion.
It is implemented.

Best,
Ernesto (Tito)
